config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'home#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true
  validates :country_of_origin, presence: true

  before_save(:titleize_product, presence: name, uniqueness: true)

  private

  def titleize_product
    self.name = self.name.titleize
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :content_body, presence: true
  validates :rating, presence: true
  validates_length_of :content_body, in: 50...251
  validates_numericality_of :rating, less_than_or_equal_to: 5
  validates_numericality_of :rating, greater_than_or_equal_to: 1
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reviews, dependent: :destroy
  # validates :username, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# This is a controller for the main landing/home page.
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/controllers/products_controller.rb
# Controller class for products
class ProductsController < ApplicationController
  before_action :only => [:new, :edit, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product successfully created'
      redirect_to products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = 'Product successfully updated'
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:alert] = 'Product successfully deleted'
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
# Controller class for reviews that are associated with products.
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review[:user_id] = current_user.id
    if @review.save
      flash[:notice] = 'Review successfully added'
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = 'Review successfully updated'
      redirect_to product_path(@review.product)
    else
      @product = Product.find(params[:product_id])
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:alert] = 'Review successfully deleted'
    redirect_to product_path(@review.product)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content_body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h3>Kent Farms is a local farm here in Smallville Kansas that mostly does Dairy and Cow products</h3>
<p>Kent Farms prides itself on the quality of its products. If we don't grow it here locally we work with other small farms around the globe to import those foods for you. We make sure that all of our farms are small independent farms so that we can help each other and keep local farmers in business, not only here in Kansas, but around the globe.
<%= image_tag ("kent_farm.jpg"), class: "img-responsive" %>
<p>Address:</p>
<p>1234 Hickory Lane</p>
<p>Smallville, Kansas 66605</p>

<div id="dccomics">
  <p>Clark Kent, Superman, and other referenced DC comics characters are copyrights of Warner Media. They are used in this project for entertainment and educational purposes.</p>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<h1>Enter a Product</h1>
<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>

  <%= f.submit %>
<% end %>

<p><%= link_to "products", products_path %></p>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<h1>Enter a Review</h1>
<%= form_for [@product, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpecialtyFoods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% content_for(:navbar) do %>
    <li><a href="/">Home</a></li>
    <li><a href="/prodcuts">Products</a></li>
    <li><a href="/products/new">New Product</a></li>
    <li><a href="/review/new">New Reviews</a></li>
  <% end %>

  <div class="jumbotron">
    <h1 class="display-4">Kent Farms</h1>
    <p class="lead">Welcome to Kent Farms!</p>
    <hr class="my-4">
    <p>For all of your local grocery needs. Locally sourced and specialty imports</p>
    <p class="lead">
    </p>

  </div>
  <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Menu</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/products">Products <span class="sr-only">(current)</span></a></li>
              <% if current_user && current_user.admin %>
                <li class="active"><a href="/admin">Admin <span class="sr-only">(current)</span></a></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><a href="/users/edit"><span class="glyphicon glyphicon-update"></span> Update Account</a></li>
                <li><a href="/users/sign_out" data-method="delete"><%= current_user.email %> <span class="glyphicon glyphicon-log-out"></span></a></li>
              <% else %>
                <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Products</h1>

<% if current_user && current_user.admin %>
<p><%= link_to "Create new product", new_product_path %></p>
<% end %>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h2>$<%= @product.price %></h2>
<h2><%= @product.country_of_origin %></h2>

<div id="review">
  <% if @product.reviews.any? %>
    <h3>Here are the reviews for this product:</h3>

    <% @product.reviews.each do |review| %>
      <ul>
        <li>
          <%= link_to review.user.email, product_review_path(@product, review) %>
        </li>
      </ul>
    <% end %>
  <% else %>
    <p>No reviews are listed for this product.</p>
  <% end %>
</div>
<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<% if current_user && current_user.admin %>
<p><%= link_to "Edit", edit_product_path(@product) %></p>

<p><%= link_to "Delete", product_path(@product),
                        :data => {:confirm => "You sure?",
                                  :method => "delete"} %></p>
<% end %>
<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>New Review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Product: <%= @product.name %></h1>
<h2>Reviewer: <%= @review.user.email %></h2>
<h2>Rating: <%= @review.rating %></h2>

<p><%= @review.content_body %></p>
<% if current_user && current_user.admin %>
<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                                :data => {:confirm => "Are you sure?",
                                          :method => "delete"} %></p>
<% end %>
<p><%= link_to "Return to product", product_path(@product) %></p>